<Goal>
<MainClass>
<ClassDeclaration>
<Identifier>
<Statement>
<VarDeclaration>
<MethodDeclaration>
<Type>
<Expression>

<OptIdentifier>
<StarVarDeclaration>
<StarParams>
<OptParams>
<StarStatement>
<ChooseOperator>
<StarExpression>
<OptExpression>
<StarMethodDeclaration>
<StarClassDeclaration>